### ISSUE TITLE
Implement a permanent IP ban

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/demo.activeadmin.info#14]
We ultimately need a permanent IP ban to prevent the unending spam. Preferably the list would be stored on disk, but on Heroku you can't rely on that for persistent storage. That seems to only leave the database. The problem with that is the database itself isn't meant to be permanent; the demo app comes with a rake task to build data so there's something to look at.

A messy workaround would be to update the rake task to copy any IPs currently in the database, then to re-insert them when the database is re-seeded.

**Comment by timoschilling** [comment]
In #23 we have preferred a different solution #21
