### ISSUE TITLE
undefined method `span_size' for #<Arbre::HTML::TextNode:0xaf250ddc>

### ISSUE THREAD

**Issue by gabrielcaires** [activeadmin/demo.activeadmin.info#15]
activeadmin (1.0.0.pre)

When I have 2 'columns' on same page, rails throws this message:
undefined method `span_size' for #<Arbre::HTML::TextNode:0xaf250ddc>

Here's an example:
```

ActiveAdmin.register_page "Dashboard" do
  	menu :priority => 1, :label => proc{ I18n.t("active_admin.dashboard") }

	content :title => proc{ I18n.t("active_admin.dashboard") } do
		columns do
		
		end
		columns do 

		end
	end
end
```

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
