### ISSUE TITLE
How to deal with comments

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/demo.activeadmin.info#23]
I think the timeouts come from to much comments in the database.

Since now we have a Heroku scheduler wich deletes the comments each hour.

I have following the logs during the first scheduler run, before it starts we have 99% timeouts, ~1 minute after the run the timeouts going down to 0%.

There are 3 way to go for the future:
1. turing off comments (#22)
2. IP blocking (#14)
3. login required comments (#21)
4. Comment Captcha
5. cleanup
  1. delete all comments each hour (current behavior)
  2. delete comments older then x hours each hour

My opinions are:
1. it reduce the fictionality :-1: 
2. it never catch all IP's and sometimes to many :-1: 
3. will stop users from trying the demo :-1: 
4. it's ok, but nobody likes Captchas :-1: 
5. 
  1. can result in adding a comment and don't seeing it :-1: 
  2. removing old comments should not disturb anybody :+1: 

I'm interested in, what others think about this? // cc: @seanlinsley, @pcreux, @eshaiju

**Comment by pcreux** [comment]
I like the idea of logging in using Github. I am wondering if using Cloudflare or so wouldn't help with preventing bots. Clouflare seems to prevent "attacks"...

**Comment by seanlinsley** [comment]
I think it's fine to require Github OAuth login (#21) since 99% of people looking to use ActiveAdmin are going to have a Github account. We just need to make sure not to:
- request anything but the most basic of permissions
- store the OAuth private key in the repo (it should be stored in [`heroku config`](https://devcenter.heroku.com/articles/config-vars))

**Comment by timoschilling** [comment]
@seanlinsley you mean "not in the repo" right? If yes, I agree with you

**Comment by pcreux** [comment]
Yes, it was a list of things *not* to do with double negations. :)

**Comment by timoschilling** [comment]
Sorry, I didn't read the **not** in "We just need to make sure not to:"

**Comment by timoschilling** [comment]
I'm closing this, there is still the #21
