### ISSUE TITLE
Update to Latest Active Admin Version?

### ISSUE THREAD

**Issue by troystarwalt** [activeadmin/demo.activeadmin.info#28]
Think it is worth updating this to the latest version of Active Admin? I know that you guys have been working on a lot of stuff for ActiveAdmin, so it may be useful to update this. Happy to take a stab at it too.

**Comment by varyonic** [comment]
Sure, you can see what I did for the last release, bump it to pre5 and Rails 5.0.  A 5.1 release will be coming... soonish.
