### ISSUE TITLE
Styling of button

### ISSUE THREAD

**Issue by besi** [activeadmin/demo.activeadmin.info#37]
A minor issue but worth noting.

This happened on my iPad in Safari running iOS 11.

![075c8d1d-d778-4f6e-92c6-d8091077721b](https://user-images.githubusercontent.com/160412/31165435-5e42b7b6-a8eb-11e7-97c8-0ccbca3a711f.jpeg)

**Comment by varyonic** [comment]
Did you try toggling Experimental WebKit CSS features under Safari Advanced settings? @javierjulio
