### ISSUE TITLE
CUSTOMIZING FILTERS

### ISSUE THREAD

**Issue by RajeshReddyM** [activeadmin/demo.activeadmin.info#5]
I need to customize filters which are shown in the sidebar pane a new filter named **SELECT** should be available as a select  list which contains the numbers showing the records to be displayed on that page.
By default Active admin displays 30 records in the interface . in that select list i will be having numbers like 10 20 30... and if i select a number say 10 from select list , the interface should display 10 records only

**Comment by timoschilling** [comment]
If this question is still up to date, take a look on the `active_admin_pagination` gem or ask on the https://github.com/activeadmin/activeadmin issue tracker
