### ISSUE TITLE
"Fork" the heroku app so we have full permissions

### ISSUE THREAD

**Issue by deivid-rodriguez** [activeadmin/demo.activeadmin.info#78]
In order to enable continuous deployment and review apps in the app, we need ownership permissions. Unfortunately, only @gregbell has that, and he's been unreachable for a long time.

As originally suggested by @javierjulio in https://github.com/activeadmin/demo.activeadmin.info/pull/67#issuecomment-451997251_suggested:

> @deivid-rodriguez do you know if you have access to change the domain for that Heroku app? If we do, I wonder if it would just be easier for us to create a new Heroku app and deploy the demo app there. That way full ownership is shared amongst the maintainers.

We can try forking the app and pointing the domain to the new app.

For now I've deployed the latest master but I'm also opening a new issue to keep track of the progress on this.

**Comment by deivid-rodriguez** [comment]
I think so too, we'll see! :+1:

**Comment by deivid-rodriguez** [comment]
I created a copy of the current application at https://demo-activeadmin-owned.herokuapp.com/. I'll see if I can switch the domains next.

**Comment by deivid-rodriguez** [comment]
This is already done. I'll be leaving the old application now to avoid confusions :)

**Comment by javierjulio** [comment]
You mean you'll be deleting the old app right? Sorry, I read "leaving" as in "leaving it alone" when that wouldn't make sense to avoid confusion. 😂

**Comment by deivid-rodriguez** [comment]
I mean remove myself as a contributor, not leaving it there... :sweat_smile:  Although we have to leave it there since we have no privileges to remove it,that's why we forked it :)

I removed myself as a contributor so I don't have the 2 apps with similar names in my list and I don't do actions on the wrong one... :sweat_smile:.

**Comment by javierjulio** [comment]
Haha oh yeah I forgot. 🙄 That makes sense, thanks! I checked my Heroku and made sure I'm only on the new one, so all good here. 👍🏻

**Comment by deivid-rodriguez** [comment]
We already did this, and although last year @gregbell showed up temporarily, we made no progress on going back to the old application. I'll close this since we now have full permissions on the new app.
